name: istt_university
description: "Institute of Science, Trade & Technology (ISTT) routine management system"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  get: ^4.6.6
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_date_timeline: ^1.1.3
  alarm: ^3.1.7
  awesome_snackbar_content: ^0.1.4
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0

  #Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_ui_auth: ^1.14.0
  firebase_in_app_messaging: ^0.8.0+8


dependency_overrides:
  win32: ^5.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/



flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  background_color: "#ffffff"


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

